version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    volumes:
      - type: bind # atualiza os arquivos dentro do container
        source: ./frontend
        target: /app-frontend
    tty: true # executa o container continuamente
    # Os `healthcheck` devem garantir que a aplicação está
    # operacional antes de liberar o container
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
